
// The following is auto-generated by a dev site creation script.

$conf['theme_debug'] = TRUE;

// ini_set('memory_limit', '256M');

$conf['file_temporary_path'] = '../tmp';

$databases['default']['default'] = array(
  'driver' => 'mysql',
  'database' => 'DB_NAME',
  'username' => 'DEV_MYSQL_USER',
  'password' => 'DEV_MYSQL_PASS',
  'prefix' => 'DB_PREFIX',
  'host' => 'localhost',
  'collation' => 'utf8_general_ci',
);

