#!/bin/bash

SCRIPTS_DIR="$(dirname "$(readlink "$0")")"

source "$SCRIPTS_DIR/../settings/settings.conf";

DB_NAME_REGEX=$(echo "[\"\'\%\$\#\@\.-]") #match the first number in a version number
DB_NAME_UNESCAPED=''
DB_NAME_CLEAN=''

while [[ $# -gt 0 ]]
do
	key="$1"
	case $key in
		-n|--project-name|--project)
		DB_NAME_UNESCAPED=$2
		shift
		;;
		-c|--project-clean)
		DB_NAME_CLEAN=$2
		shift
		;;
		-u|--db-user)
		DB_USER=$2
		shift
		;;
		-m|--mysql-user)
		MYSQL_USER=$2
		shift
		;;
		-p|--mysql-password)
		MYSQL_PW=$2
		shift
		;;
		-t|--template-script-location)
		DEFAULT_DB_SCRIPT=$2
		shift
		;;
		-d|--db-scripts-location)
		DB_SCRIPT_LOCATION=$2
		shift
		;;
		*)
		echo "createdrupaldb: unknown option " $1
		exit 1
		;;
	esac
	shift
done


if [ "$DB_NAME_CLEAN" == "" ]; then
	if [ "$DB_NAME_UNESCAPED" == "" ]; then
		while :
		do
			read -p "Project name not provided, please provide it now: " answer
			if [ "$answer" != "" ]; then
				CLEAN=$( echo "$answer" | sed "s/$DB_NAME_REGEX/_/g" )
				read -p "Using $CLEAN as the database name, is this ok? (y/n) " continuecreation
				if [ "$continuecreation" == "y" ]; then
					DB_NAME_CLEAN=$CLEAN
					break
				else
					echo "Try another database name."
				fi
			fi
		done
	else
		while :
		do
			CLEAN=$( echo "$DB_NAME_UNESCAPED" | sed "s/$DB_NAME_REGEX/_/g" )
			read -p "Using $CLEAN as the database name, is this ok? (y/n) " continuecreation
			if [ "$continuecreation" == "y" ]; then
				DB_NAME_CLEAN=$CLEAN
				break
			else
				echo "Try another database name."
			fi
		done
	fi
fi

if [ "$DB_USER" == "" ]; then
	while :
	do
		read -p "Dev Myqsl user not provided, please provide it now: " answer
		if [ "$answer" != "" ]; then
			DB_USER=$answer
			break
		fi
	done
fi

if [ "$MYSQL_USER" == "" ]; then
	while :
	do
		read -p "Mysql user not provided, please provide it now: " answer
		if [ "$answer" != "" ]; then
			MYSQL_USER=$answer
			break
		fi
	done
fi

if [ "MYSQL_PW" == "" ]; then
	read -s -p "Mysql pw for $MYSQL_USER not provided, please provide it now: " MYSQL_PW
fi

if [ "$DEFAULT_DB_SCRIPT" == "" ]; then
	while :
	do
		read -p "Default db creation script not provided, please provide it now: " answer
		if [ "$answer" != "" ]; then
			DEFAULT_DB_SCRIPT=$answer
			break
		fi
	done
fi

if [ "$DB_SCRIPT_LOCATION" == "" ]; then
	while :
	do
		read -p "Db creation script directory not provided, please provide it now: " answer
		if [ "$answer" != "" ]; then
			DB_SCRIPT_LOCATION=$answer
			break
		fi
	done
fi

PROJECT_SCRIPT_LOCATION="$DB_SCRIPT_LOCATION/$DB_NAME_CLEAN.database_create.sql"

echo "Mysql may require password..."
sed "s/TMP_DEV_DB_NAME/$DB_NAME_CLEAN/g" "$DEFAULT_DB_SCRIPT" | sed "s/TMP_DEV_USERNAME/$DB_USER/g" > "$PROJECT_SCRIPT_LOCATION"
mysql -u $MYSQL_USER -p$MYSQL_PW < "$PROJECT_SCRIPT_LOCATION" 2>/dev/null
echo "Created database."
echo "db name: $DB_NAME_CLEAN"
echo "db user: $DB_USER"
