#!/bin/bash

# arg 1: Drupal version
# arg 2: Download location

VERSION=''
DLLOC=''

while [[ $# -gt 0 ]]
do
	key="$1"
	case $key in
		-v|--download-version)
		VERSION=$2
		shift
		;;
		-l|--download-location)
		DLLOC=$2
		shift
		;;
		*)
		echo "dldrupal: unknown option " $1
		exit 1
		;;
	esac
	shift
done

if [ "$VERSION" == "" ]; then
	read -p "Drupal Version not provided, please provide it now: " VERSION
fi

if [ "$DLLOC" == "" ]; then
	read -p "Download Location not provided, please provide it now: " DLLOC
fi

CURRENT_DIR=$(pwd)
DLLOC=$( echo $DLLOC | sed s$'\001''~'$'\001'"$HOME"$'\001''g')
cd $DLLOC
echo "Downloading drupal version $VERSION to $DLLOC"
wget $(echo "https://www.drupal.org/files/projects/drupal-$VERSION.tar.gz") -q --show-progress

if [ ! -e "drupal-$VERSION.tar.gz" ]; then
	echo "Couldn't download files. Exiting."
	exit 1
fi

tar -xzf $(echo "drupal-$VERSION.tar.gz")
mv "$DLLOC/drupal-$VERSION"/{.[!.],}* "$DLLOC" # Move all files and hidden files
rm -r "$DLLOC/drupal-$VERSION"
rm "$DLLOC/drupal-$VERSION.tar.gz"
echo "Project files downloaded."
cd "$CURRENT_DIR"
exit 0
